"""
Install launcher script for Nuke Plugin Manager.

Creates a double-clickable macOS .app bundle in ~/.nuke/Nuke_Plugin_Manager/ that launches
the Plugin Manager app without requiring Nuke or Terminal.
"""

import os
import stat
from pathlib import Path


def main():
    """Create the macOS .app bundle in ~/.nuke/Nuke_Plugin_Manager/."""
    # Get installable folder root (parent of core/ directory)
    installable_root = Path(__file__).parent.parent.resolve()
    app_py = installable_root / "core" / "app.py"

    # Verify app.py exists
    if not app_py.exists():
        print(f"Error: app.py not found at {app_py}")
        return 1

    # Determine Python executable
    # Look for venv in installable root, or parent (repo root)
    venv_python = installable_root / ".venv" / "bin" / "python"
    if not venv_python.exists():
        venv_python = installable_root.parent / ".venv" / "bin" / "python"
    if venv_python.exists():
        python_cmd = str(venv_python)
    else:
        python_cmd = "python3"

    # Create ~/.nuke/Nuke_Plugin_Manager/ directory if it doesn't exist
    plugin_manager_dir = Path.home() / ".nuke" / "Nuke_Plugin_Manager"
    plugin_manager_dir.mkdir(parents=True, exist_ok=True)

    # .app bundle path
    app_bundle = plugin_manager_dir / "Nuke_Plugin_Manager_Panel.app"
    contents_dir = app_bundle / "Contents"
    macos_dir = contents_dir / "MacOS"
    executable_path = macos_dir / "Nuke_Plugin_Manager_Panel"

    try:
        # Create directory structure
        macos_dir.mkdir(parents=True, exist_ok=True)

        # Create Info.plist
        info_plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleName</key>
    <string>Nuke Plugin Manager Panel</string>
    <key>CFBundleIdentifier</key>
    <string>com.nuke.pluginmanager</string>
    <key>CFBundleExecutable</key>
    <string>Nuke_Plugin_Manager_Panel</string>
    <key>LSBackgroundOnly</key>
    <false/>
</dict>
</plist>
"""
        info_plist_path = contents_dir / "Info.plist"
        with open(info_plist_path, 'w') as f:
            f.write(info_plist_content)

        # Create executable script
        executable_content = f"""#!/bin/bash
# Launcher for Nuke Plugin Manager
# Generated by install_launcher.py
# Do not edit manually - re-run install_launcher.py to update

cd "{installable_root}"
nohup {python_cmd} -c "import sys; sys.path.insert(0, 'core'); from app import main; main()" >/dev/null 2>&1 &
"""
        with open(executable_path, 'w') as f:
            f.write(executable_content)

        # Make executable
        executable_path.chmod(executable_path.stat().st_mode | stat.S_IEXEC)

        print(f"Launcher installed successfully!")
        print(f"Location: {app_bundle}")
        print(f"\nYou can now double-click 'Nuke_Plugin_Manager_Panel.app' to launch the Plugin Manager.")

        return 0

    except (IOError, OSError, PermissionError) as e:
        print(f"Error: Failed to create launcher: {e}")
        return 1


if __name__ == "__main__":
    exit(main())
