"""
Install launcher script for Nuke Plugin Manager.

Creates a platform-specific double-clickable launcher in ~/.nuke/Nuke_Plugin_Manager/:
- macOS: .app bundle
- Windows: .bat file
- Linux: .desktop file + shell script
"""

import os
import platform
import stat
import sys
from pathlib import Path


def _get_python_command(installable_root: Path) -> str:
    """Determine the Python executable to use."""
    # Look for venv in installable root, or parent (repo root)
    if platform.system() == "Windows":
        venv_python = installable_root / ".venv" / "Scripts" / "python.exe"
        if not venv_python.exists():
            venv_python = installable_root.parent / ".venv" / "Scripts" / "python.exe"
    else:
        venv_python = installable_root / ".venv" / "bin" / "python"
        if not venv_python.exists():
            venv_python = installable_root.parent / ".venv" / "bin" / "python"

    if venv_python.exists():
        return str(venv_python)
    elif platform.system() == "Windows":
        return "python"
    else:
        return "python3"


def _create_macos_launcher(installable_root: Path, plugin_manager_dir: Path, python_cmd: str) -> bool:
    """Create macOS .app bundle launcher."""
    app_bundle = plugin_manager_dir / "Nuke_Plugin_Manager_Panel.app"
    contents_dir = app_bundle / "Contents"
    macos_dir = contents_dir / "MacOS"
    executable_path = macos_dir / "Nuke_Plugin_Manager_Panel"

    try:
        # Create directory structure
        macos_dir.mkdir(parents=True, exist_ok=True)

        # Create Info.plist
        info_plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleName</key>
    <string>Nuke Plugin Manager Panel</string>
    <key>CFBundleIdentifier</key>
    <string>com.nuke.pluginmanager</string>
    <key>CFBundleExecutable</key>
    <string>Nuke_Plugin_Manager_Panel</string>
    <key>LSBackgroundOnly</key>
    <false/>
</dict>
</plist>
"""
        info_plist_path = contents_dir / "Info.plist"
        with open(info_plist_path, 'w') as f:
            f.write(info_plist_content)

        # Create executable script
        executable_content = f"""#!/bin/bash
# Launcher for Nuke Plugin Manager
# Generated by install_launcher.py
# Do not edit manually - re-run install_launcher.py to update

cd "{installable_root}"
nohup {python_cmd} -c "import sys; sys.path.insert(0, 'core'); from app import main; main()" >/dev/null 2>&1 &
"""
        with open(executable_path, 'w') as f:
            f.write(executable_content)

        # Make executable
        executable_path.chmod(executable_path.stat().st_mode | stat.S_IEXEC)

        print(f"macOS launcher installed successfully!")
        print(f"Location: {app_bundle}")
        print(f"\nYou can now double-click 'Nuke_Plugin_Manager_Panel.app' to launch the Plugin Manager.")
        return True

    except (IOError, OSError, PermissionError) as e:
        print(f"Error: Failed to create macOS launcher: {e}")
        return False


def _create_windows_launcher(installable_root: Path, plugin_manager_dir: Path, python_cmd: str) -> bool:
    """Create Windows .bat file launcher."""
    launcher_path = plugin_manager_dir / "Nuke_Plugin_Manager_Panel.bat"

    try:
        # Create batch file
        bat_content = f"""@echo off
REM Launcher for Nuke Plugin Manager
REM Generated by install_launcher.py
REM Do not edit manually - re-run install_launcher.py to update

cd /d "{installable_root}"
start "" {python_cmd} -c "import sys; sys.path.insert(0, 'core'); from app import main; main()"
"""
        with open(launcher_path, 'w', encoding='utf-8') as f:
            f.write(bat_content)

        print(f"Windows launcher installed successfully!")
        print(f"Location: {launcher_path}")
        print(f"\nYou can now double-click 'Nuke_Plugin_Manager_Panel.bat' to launch the Plugin Manager.")
        return True

    except (IOError, OSError, PermissionError) as e:
        print(f"Error: Failed to create Windows launcher: {e}")
        return False


def _create_linux_launcher(installable_root: Path, plugin_manager_dir: Path, python_cmd: str) -> bool:
    """Create Linux .desktop file and shell script launcher."""
    script_path = plugin_manager_dir / "Nuke_Plugin_Manager_Panel.sh"
    desktop_path = plugin_manager_dir / "Nuke_Plugin_Manager_Panel.desktop"

    try:
        # Create shell script
        script_content = f"""#!/bin/bash
# Launcher for Nuke Plugin Manager
# Generated by install_launcher.py
# Do not edit manually - re-run install_launcher.py to update

cd "{installable_root}"
{python_cmd} -c "import sys; sys.path.insert(0, 'core'); from app import main; main()" &
"""
        with open(script_path, 'w') as f:
            f.write(script_content)

        # Make script executable
        script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC)

        # Create .desktop file
        desktop_content = f"""[Desktop Entry]
Version=1.0
Type=Application
Name=Nuke Plugin Manager Panel
Comment=Manage Nuke plugins
Exec={script_path}
Icon=application-x-executable
Terminal=false
Categories=Utility;Development;
"""
        with open(desktop_path, 'w') as f:
            f.write(desktop_content)

        # Make desktop file executable (required for some desktop environments)
        desktop_path.chmod(desktop_path.stat().st_mode | stat.S_IEXEC)

        print(f"Linux launcher installed successfully!")
        print(f"Location: {script_path}")
        print(f"Desktop entry: {desktop_path}")
        print(f"\nYou can now:")
        print(f"  - Double-click 'Nuke_Plugin_Manager_Panel.desktop' (if supported)")
        print(f"  - Run: {script_path}")
        return True

    except (IOError, OSError, PermissionError) as e:
        print(f"Error: Failed to create Linux launcher: {e}")
        return False


def main():
    """Create platform-specific launcher in ~/.nuke/Nuke_Plugin_Manager/."""
    # Get installable folder root (parent of core/ directory)
    installable_root = Path(__file__).parent.parent.resolve()
    app_py = installable_root / "core" / "app.py"

    # Verify app.py exists
    if not app_py.exists():
        print(f"Error: app.py not found at {app_py}")
        return 1

    # Determine Python executable
    python_cmd = _get_python_command(installable_root)

    # Create ~/.nuke/Nuke_Plugin_Manager/ directory if it doesn't exist
    plugin_manager_dir = Path.home() / ".nuke" / "Nuke_Plugin_Manager"
    plugin_manager_dir.mkdir(parents=True, exist_ok=True)

    # Create platform-specific launcher
    system = platform.system()
    success = False

    if system == "Darwin":  # macOS
        success = _create_macos_launcher(installable_root, plugin_manager_dir, python_cmd)
    elif system == "Windows":
        success = _create_windows_launcher(installable_root, plugin_manager_dir, python_cmd)
    elif system == "Linux":
        success = _create_linux_launcher(installable_root, plugin_manager_dir, python_cmd)
    else:
        print(f"Error: Unsupported platform: {system}")
        print(f"Please run the app directly: {python_cmd} {app_py}")
        return 1

    return 0 if success else 1


if __name__ == "__main__":
    exit(main())
